# GitHub Pages configuration file

# Set the Jekyll theme to use
theme: minima

# Exclude unnecessary files from being built
exclude:
  - node_modules/
  - scripts/
  - tests/
  - .github/
  - package.json
  - package-lock.json
  - .gitignore
  
# URL setup
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
